services:
  postgres:
    image: postgres:latest
    container_name: microservices-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pp@9091$
      POSTGRES_DB: microservices
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-database.sql:/docker-entrypoint-initdb.d/init-database.sql
    networks:
      - microservices-network


volumes:
  postgres_data:

networks:
  microservices-network:
    driver: bridge